name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@1.1.0

    - name: Run linters
      uses: wearerequired/lint-action@v1

    - name: Run write good
      uses: btford/write-good@v1
